### ISSUE TITLE
At first install of dev environment, get toast error 'No game in'

### ISSUE THREAD

**Issue by gwhizoftv** [cdot/Xanado#59]
When installing the dev environment, there are no games yet.
When connecting to the server, we get a popup with this:
![Screen Shot 2022-10-02 at 2 14 29 PM](https://user-images.githubusercontent.com/94144702/193476640-92745c48-7098-42ab-b8a9-58f48d969cdf.png)

and in the console:

`Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Replay.js:23:24
    at Game.js:33:27
    at Object.execCb (require.js:1696:33)
    at Module.check (require.js:883:51)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)`

and the code there:

`define([
  "platform", "common/Utils",
  "common/Types", "game/LetterBag", "game/Board",
  "game/Player", "game/Tile", "game/Rack", "game/Turn"
], (
  Platform, Utils,
  Types, LetterBag, Board,
  Player, Tile, Rack, Turn
) => {

  const Turns = Types.Turns;
  const State = Types.State;

  /**
   * Extend Game to support replay of another game
   * @mixin Replay
   */
  return superclass => class Replay extends superclass { <<<<<---- here

    /*
     `
**To Reproduce**
1. Clone the repo
2. npm install
3. npm run server

**Expected behavior**
There should be no popup and the app should be OK.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Monterey
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 105.0.5195.125 (Official Build) (x86_64)

Is this because of running on MacOS ?

**Comment by gwhizoftv** [comment]
It appears by changing to game.js, it fixed this too!
