### ISSUE TITLE
exception in new code

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#71]
Getting this when tried the latest master.  Believe it was the same with 3.0

Error: Tried loading "backend/BackendGame" at /home/nodejs/Xanado-master/backend/BackendGame.js then tried node's require("backend/BackendGame") and it failed with error: Error: Cannot find module 'backend/BackendGame'
Require stack:
- /home/nodejs/Xanado-master/server.js
    at /home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:2600:27
    at Object.execCb (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1946:33)
    at Module.check (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1133:51)
    at Module.enable (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1426:22)
    at Module.init (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1038:26)
    at callGetModule (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1453:63)
    at Object.completeLoad (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1840:21)
    at Function.req.load (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:2613:17)
    at Object.load (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1935:21)
    at Module.load (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1084:29) {
  originalError: Error: Cannot find module 'backend/BackendGame'
  Require stack:
  - /home/nodejs/Xanado-master/server.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
      at Function.Module._load (internal/modules/cjs/loader.js:746:27)
      at Module.require (internal/modules/cjs/loader.js:974:19)
      at require (internal/modules/cjs/helpers.js:101:18)
      at /home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:2598:75
      at Object.execCb (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1946:33)
      at Module.check (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1133:51)
      at Module.enable (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1426:22)
      at Module.init (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1038:26)
      at callGetModule (/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:1453:63) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [ '/home/nodejs/Xanado-master/server.js' ]
  },
  moduleName: 'backend/BackendGame',
  requireModules: [ 'backend/BackendGame' ]
}
/home/nodejs/Xanado-master/node_modules/requirejs/bin/r.js:2607
                    throw err;
                    ^

**Comment by cdot** [comment]
From the backtrace it looks like you are trying to run an old version of server.js - are you trying to run the Docker image?

**Comment by pkolano** [comment]
sorry, tried to upgrade a few minutes before our game and now see that things had changed locations, etc. so was mixing and matching version.   it works ok with a fresh install.
